# Generated by Django 4.2.11 on 2024-05-07 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"verbose_name": "ответ", "verbose_name_plural": "ответы"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "вопрос", "verbose_name_plural": "вопросы"},
        ),
        migrations.AlterModelOptions(
            name="test",
            options={"verbose_name": "тест", "verbose_name_plural": "тесты"},
        ),
        migrations.AlterModelOptions(
            name="usertest",
            options={
                "verbose_name": "результат теста пользователя",
                "verbose_name_plural": "результаты тестов пользователей",
            },
        ),
        migrations.AlterModelOptions(
            name="usertestresult",
            options={
                "verbose_name": "результат по вопросу",
                "verbose_name_plural": "результаты по вопросам",
            },
        ),
        migrations.AlterField(
            model_name="answer",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="answer_images/",
                verbose_name="картинка",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(default=False, verbose_name="является верным"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="testing.question",
                verbose_name="вопросы",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="text",
            field=models.CharField(max_length=255, verbose_name="текст"),
        ),
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("EASY", "Легкий"),
                    ("MEDIUM", "Средний"),
                    ("HARD", "Сложный"),
                ],
                max_length=20,
                verbose_name="сложность вопроса",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(verbose_name="текст вопроса"),
        ),
        migrations.AlterField(
            model_name="test",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
        ),
        migrations.AlterField(
            model_name="test",
            name="description",
            field=models.TextField(
                blank=True, max_length=255, null=True, verbose_name="описание"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=30, verbose_name="продолжительность"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="test_images/", verbose_name="картинка"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="questions",
            field=models.ManyToManyField(
                related_name="tests", to="testing.question", verbose_name="вопросы"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Активен"), ("NOT_ACTIVE", "Не активен")],
                default="ACTIVE",
                max_length=20,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="title",
            field=models.CharField(max_length=255, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="test",
            name="users",
            field=models.ManyToManyField(
                related_name="tests",
                through="testing.UserTest",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователи",
            ),
        ),
        migrations.AlterField(
            model_name="usertest",
            name="completed",
            field=models.BooleanField(default=False, verbose_name="завершен"),
        ),
        migrations.AlterField(
            model_name="usertest",
            name="end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="время завершения"
            ),
        ),
        migrations.AlterField(
            model_name="usertest",
            name="start_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="время начала"
            ),
        ),
        migrations.AlterField(
            model_name="usertest",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usertests",
                to="testing.test",
                verbose_name="тесты",
            ),
        ),
        migrations.AlterField(
            model_name="usertest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usertests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователи",
            ),
        ),
        migrations.AlterField(
            model_name="usertestresult",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userteststesults",
                to="testing.question",
                verbose_name="вопрос",
            ),
        ),
        migrations.AlterField(
            model_name="usertestresult",
            name="selected_answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userstestresults",
                to="testing.answer",
                verbose_name="выбранный ответ",
            ),
        ),
        migrations.AlterField(
            model_name="usertestresult",
            name="user_test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usertestresults",
                to="testing.usertest",
                verbose_name="пользователь-тест",
            ),
        ),
    ]
