# Generated by Django 4.2.11 on 2024-05-14 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("testing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_tests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор",
            ),
            preserve_default=False,
        ),
    ]
