# Generated by Django 4.2.11 on 2024-05-14 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("testing", "0002_test_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_answers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_questions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор",
            ),
            preserve_default=False,
        ),
    ]
