# Generated by Django 4.2.11 on 2024-05-07 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testing", "0002_alter_answer_options_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertest",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usertests",
                to="testing.test",
                verbose_name="тест",
            ),
        ),
        migrations.AlterField(
            model_name="usertest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usertests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
