# Generated by Django 4.2.11 on 2024-05-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testing", "0003_answer_author_question_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="тема"),
                ),
            ],
            options={
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
            },
        ),
        migrations.AddField(
            model_name="test",
            name="tag",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="test_tags",
                to="testing.tag",
                verbose_name="теги",
            ),
        ),
    ]
