# Generated by Django 4.2.11 on 2024-05-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testing", "0004_tag_test_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("EASY", "Легкий"),
                    ("MEDIUM", "Средний"),
                    ("HARD", "Сложный"),
                ],
                default=1,
                max_length=20,
                verbose_name="сложность теста",
            ),
            preserve_default=False,
        ),
    ]
