# Generated by Django 4.2.11 on 2024-05-17 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testing", "0006_tag_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="tag",
        ),
    ]
