# Generated by Django 4.2.11 on 2024-05-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testing", "0007_remove_test_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="test",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="testing.test", verbose_name="тесты"
            ),
        ),
    ]
